In [2]:
# Import Pandas. Pandas is a Python library used for working with data sets.

In [3]:
import pandas as pd

In [7]:
# Import most recent July 24, 2026 financials from Voter Focus for Zeman and then for Azim. 
# Create a dataframe. 
## A Pandas DataFrame is a 2 dimensional data structure, like a 2 dimensional array, or a table with rows and columns.

In [8]:
dfzeman = pd.read_csv("Copy_Zeman_CFinExport_072426.csv")

In [9]:
dfzeman

,rpt code,line number,item date,Cont/Exp,name,address 1,address 2,city,state,zip,cont. type,occupation,item type,description,amount,Amend. code,lastname
0,57428,1,2026-01-31,E,Anedot Inc,1340 Poydras Street Suite 1770,NaN,New Orleans,LA,70112.0,NaN,NaN,MO,Credit Card Collection Fee,40.30,NaN,Anedot Inc
1,57428,1,2026-01-31,C,Allen Zeman,***Protected Voter***,NaN,NaN,NaN,NaN,I,SCHOOL<br>BOARD<br>MEMBER,CH,NaN,1000.00,NaN,Zeman
2,57428,12,2026-02-02,C,Yvonne Garth,5595 Orange Dr #202,NaN,Davie,FL,33314.0,I,Program<br>Management,CH,NaN,1000.00,NaN,Garth
3,57428,13,2026-02-03,C,Bierman PL Weiss Serota Helfman Cole,2800 Ponce de Leon Blvd STE 1200,NaN,Coral Gables,FL,33134.0,B,Law Firm,CH,NaN,1000.00,NaN,Weiss Serota Helfman Cole
4,57428,20,2026-02-04,C,Barron Channer,1101 Brickell Ave #310-697,NaN,Miami,FL,33231.0,I,Business<br>Owner,CH,NaN,1000.00,NaN,Channer
5,57428,19,2026-02-04,C,David Bjorklund,10295 150th Ct N,NaN,Jupirer,FL,33478.0,I,Professor,CH,NaN,1000.00,NaN,Bjorklund
6,57428,18,2026-02-04,C,Jennifer Dimler,***Protected Voter***,NaN,NaN,NaN,NaN,I,NaN,CH,NaN,100.00,NaN,Dimler
7,57428,17,2026-02-04,C,Anthony De Meo,7726 Yosemite Ln,NaN,Parkland,FL,33067.0,I,NaN,CH,NaN,100.00,NaN,De Meo
8,57428,16,2026-02-04,C,Josh Levy,***Protected Voter***,NaN,NaN,NaN,NaN,I,Attorney,CH,NaN,500.00,NaN,Levy
9,57428,15,2026-02-04,C,Ryan Shrouder,9700 Griffin Road,NaN,Fort Lauderdale,FL,33328.0,I,Business<br>Owner,CH,NaN,250.00,NaN,Shrouder
10,57428,14,2026-02-04,C,Chuck Harper,***Protected Voter***,NaN,NaN,NaN,NaN,I,NaN,CH,NaN,100.00,NaN,Harper
11,57428,22,2026-02-08,C,David Angel,1 Longfellow Place Apt 2916,NaN,Boston,MA,21114.0,I,Business<br>Owner,CH,NaN,150.00,NaN,Angel
12,57428,21,2026-02-08,C,Blaine Templeman,3900 Galt Ocean Drive Apt 2417,NaN,Fort Lauderdale,FL,33308.0,I,Attorney,CH,NaN,1000.00,NaN,Templeman
13,57428,5,2026-02-25,C,Melinda P'Pool,3316 NE 42nd Ct,NaN,Fort Lauderdale,FL,33308.0,I,Construction,CH,NaN,1000.00,NaN,P'Pool
14,57428,2,2026-02-25,C,Corradino LLC,200 South Meridian Street Suite 330,NaN,Indianapolis,IN,46225.0,B,Construction,CH,NaN,1000.00,NaN,Corradino LLC
15,57428,3,2026-02-25,C,The Corradino Group,200 S Fith St Suite 300 N,NaN,Louisville,KY,40202.0,B,Construction,CH,NaN,1000.00,NaN,The Corradino Group
16,57428,11,2026-02-25,C,Darlene Sesto,3107 NE 21st Street,NaN,Fort Lauderdale,FL,33305.0,I,Nurse,CH,NaN,100.00,NaN,Sesto
17,57428,10,2026-02-25,C,Archibald Ryan IV,34 NW 1st Ave,NaN,Dania Beach,FL,33004.0,I,Real<br>Estate,CH,NaN,100.00,NaN,Ryan IV
18,57428,9,2026-02-25,C,Lindsey Smith,3539 Maria Theresa Ave,NaN,West Palm Beach,FL,33406.0,I,Photographer,CH,NaN,100.00,NaN,Smith
19,57428,8,2026-02-25,C,American Holding Group Inc,4325 W Sunrise Blvd,NaN,Plantation,FL,33313.0,B,Marketing<br>Consulting,CH,NaN,250.00,NaN,American Holding Group Inc
20,57428,7,2026-02-25,C,DiPompeo Construction Corp,2301 NE 33rd Court Unit 102,NaN,Pompano Beach,FL,33069.0,B,Construction,CH,NaN,300.00,NaN,DiPompeo Construction Corp
21,57428,6,2026-02-25,C,Frederick P'Pool,3316 NE 42nd Ct,NaN,Fort Lauderdale,FL,33308.0,I,Construction,CH,NaN,1000.00,NaN,P'Pool
22,57428,4,2026-02-25,C,Government Law Group PLLC,200 South Andrews Ave Ste 601,NaN,Fort Lauderdale,FL,33301.0,B,Law Firm,CH,NaN,1000.00,NaN,Government Law Group PLLC
23,57428,2,2026-02-28,E,Anedot Inc,1340 Poydras Street Suite 1770,NaN,New Orleans,LA,70112.0,NaN,NaN,MO,Credit Card Collection Fee,251.30,NaN,Anedot Inc
24,57428,25,2026-03-26,C,Thomas DiGiorgio,***Protected Voter***,NaN,NaN,NaN,NaN,I,Business<br>Owner,CH,NaN,500.00,NaN,DiGiorgio
25,57428,27,2026-03-29,C,Norman Ostrau,1901 N Ocean Blvd #8 E,NaN,Fort Lauderdale,FL,33305.0,I,Retired,CH,NaN,100.00,NaN,Ostrau
26,57428,28,2026-03-29,C,Derek Zeman,17820 113th Ter N,NaN,Jupiter,FL,33478.0,I,Land<br>Surveyor,CH,NaN,1000.00,NaN,Zeman
27,57428,26,2026-03-29,C,Jon Goodman,1600 ne 1st avenue #3409,NaN,Miami,FL,33132.0,I,CPA,CH,NaN,1000.00,NaN,Goodman
28,57428,23,2026-03-30,C,Ahhalia Bahdur,627 Warren St,NaN,Brooklyn,NY,11217.0,I,Retired,CH,NaN,200.00,NaN,Bahdur
29,57428,29,2026-03-30,C,Joseph DiRico,2001 N Ocean Blv,NaN,Fort Lauderdale,FL,33305.0,I,Retired,CH,NaN,250.00,NaN,DiRico
30,57428,24,2026-03-31,C,Euridice Lopez,3031 NE 21st Street,NaN,Fort Lauderdale,FL,33305.0,I,Retired,CH,NaN,1000.00,NaN,Lopez
31,57428,3,2026-03-31,E,Anedot Inc,1340 Poydras Street Suite 1770,NaN,New Orleans,LA,70112.0,NaN,NaN,MO,Credit Card Collection Fee,115.50,NaN,Anedot Inc
32,57493,1,2026-04-03,C,Jonathan Sommer,831 Beacon St Suite 407,NaN,Newton Center,MA,2459.0,I,Management,CH,NaN,2000.00,NaN,Sommer
33,57493,2,2026-04-12,C,Jonathan Sommer,831 Beacon St Suite 407,NaN,Newton Center,MA,2459.0,I,Management,RE,NaN,-2000.00,NaN,Sommer
34,57493,3,2026-04-13,C,Jonathan Sommer,831 Beacon St Suite 407,NaN,Newton Center,MA,2459.0,I,Management,CH,NaN,1000.00,NaN,Sommer
35,57493,4,2026-04-27,C,LSN Partners,3800 NE 1st Ave suite 200,NaN,Miami,FL,33137.0,B,Government<br>Affairs,CH,NaN,1000.00,NaN,LSN Partners
36,57493,5,2026-04-27,C,Michael McIntyre,575 NE 5th terrace Apt 743,NaN,Fort Lauderdale,FL,33301.0,I,VP program<br>manager,CH,NaN,1000.00,NaN,McIntyre
37,57493,1,2026-04-30,E,Anedot Inc,1340 Poydras Street Suite 1770,NaN,New Orleans,LA,70112.0,NaN,NaN,MO,Credit Card Collection Fee,201.20,NaN,Anedot Inc
38,57493,2,2026-05-19,E,Centennial Bank,2600 E Commercial Blvd,NaN,Fort Lauderdale,FL,33308.0,NaN,NaN,MO,Checks,232.34,NaN,Centennial Bank
39,57493,6,2026-05-29,C,Lori Parrish,12801 Luray Rd,NaN,SW Ranches,FL,33330.0,I,Retired,CH,NaN,118.00,NaN,Parrish
40,57527,1,2026-06-09,E,Elections Broward County Supervisor of,4650 NW 21st Ave,NaN,Fort Lauderdale,FL,33309.0,NaN,NaN,MO,Qualifying Fee,2263.48,NaN,Broward County Supervisor of
41,57527,2,2026-06-10,E,Bluestream Consulting LLC,5591 NE 33rd Ave,NaN,Fort Lauderdale,FL,33308.0,NaN,NaN,MO,Compliance<br>/ Printed<br>Material,6397.70,NaN,Bluestream Consulting LLC
42,57527,1,2026-06-11,C,William Walker,1366 SE 17th St,NaN,Fort Lauderdale,FL,33316.0,I,CEO Water<br>Taxi,CH,NaN,1000.00,NaN,Walker
43,57527,3,2026-06-12,E,Anedot Inc,1340 Poydras Street Suite 1770,NaN,New Orleans,LA,70112.0,NaN,NaN,MO,Credit Card Collection Fee,40.30,NaN,Anedot Inc
44,57582,1,2026-06-13,C,John Edelson,2200 N Ocean Blvd Unit N1201,NaN,Fort Lauderdale,FL,33305.0,I,Retired,CH,NaN,250.00,NaN,Edelson
45,57582,1,2026-06-17,E,Broward Democratic Party,1700 NW 66 Ave Ste 100,NaN,Plantation,FL,33313.0,NaN,NaN,MO,Event Tickets,1000.00,NaN,Broward Democratic Party
46,57582,2,2026-06-18,C,Joshua Schaffer,2219 NE 32ND AVE,NaN,Fort Lauderdale,FL,33305.0,I,Self<br>Employed,CH,NaN,500.00,NaN,Schaffer
47,57582,3,2026-06-25,C,Adam Hall,6311 Tidewater Island Cir,NaN,Fort Myers,FL,33908.0,I,Microsoft<br>Executive,CH,NaN,100.00,NaN,Hall
48,57582,2,2026-06-26,E,Anedot Inc,1340 Poydras Street Suite 1770,NaN,New Orleans,LA,70112.0,NaN,NaN,MO,Credit Card Collection Fees,34.90,NaN,Anedot Inc
49,57642,1,2026-06-30,C,EXP PAC,205 N Michigan Ave STE 3600,NaN,Chicago,IL,60601.0,F,Political<br>Committee,CH,NaN,1000.00,NaN,EXP PAC
50,57642,2,2026-07-08,C,Dave Hall,2030 17th St W PH 722-7253,NaN,Palmetto,FL,34221.0,I,Retired,CH,NaN,300.00,NaN,Hall
51,57642,3,2026-07-08,C,Steven Ganon,2517 N Atlantic Blvd,NaN,Fort Lauderdale,FL,33305.0,I,Retired,CA,NaN,50.00,NaN,Ganon
52,57642,4,2026-07-08,C,Barbie Pearson,2420 SE 17th St C402,NaN,Fort Lauderdale,FL,33316.0,I,Retired,CA,NaN,50.00,NaN,Pearson
53,57682,1,2026-07-14,C,Randa Bromiley,1310 E Terra Mar Dr,NaN,Pompano Beach,FL,33062.0,I,Retired,CH,NaN,1000.00,NaN,Bromiley
54,57682,2,2026-07-15,C,Sharry Kimmel,10657 North Lago Vista Circle,NaN,Parkland,FL,33076.0,I,Professor,CH,NaN,100.00,NaN,Kimmel
55,57682,1,2026-07-17,E,Anedot Inc,1340 Poydras Street Suite 1770,NaN,New Orleans,LA,70112.0,NaN,NaN,MO,Credit Card Collection Fee,44.60,NaN,Anedot Inc

In [10]:
dfazim = pd.read_csv("Copy_Azim_CFinExport_072426.csv")

In [11]:
dfazim

,rpt code,line number,item date,Cont/Exp,name,address 1,address 2,city,state,zip,cont. type,occupation,item type,description,amount,Amend. code,lastname
0,57437,1,2026-03-09,C,Sonja Azim,***Protected Voter***,NaN,NaN,NaN,NaN,S,Trainer,CH,NaN,100.00,NaN,Azim
1,57437,36,2026-03-10,C,Mariah Ashshakoor Snowden,631 NW 46 Ave,NaN,Plantaton,FL,33317.0,I,Independent<br>Contractor,IK,Campaign Photography,350.00,NaN,Snowden
2,57437,2,2026-03-12,C,Sonja Azim,***Protected Voter***,NaN,NaN,NaN,NaN,S,Trainer,CH,NaN,10.00,NaN,Azim
3,57437,37,2026-03-12,C,Sonja Azim,***Protected Voter***,NaN,NaN,NaN,NaN,S,Trainer,IK,printing<br>costs,17.77,NaN,Azim
4,57437,38,2026-03-13,C,Sonja Azim,***Protected Voter***,NaN,NaN,NaN,NaN,S,Trainer,IK,Campaign T shirt materials,34.13,NaN,Azim
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
236,57708,3,2026-07-14,E,AO Analytics LLC,1309 Coffeen Avenue,STE 20055,Sheridan,WY,82801.0,NaN,NaN,MO,Mass text messaging costs,4667.70,NaN,AO Analytics LLC
237,57708,1,2026-07-15,C,Dudly Etienne-Harvard,1890 SW 37 Terrace,NaN,Ft. Lauderdale,FL,33312.0,I,Self<br>Employed,CH,NaN,100.00,NaN,Etienne-Harvard
238,57708,2,2026-07-15,C,Ilona Holmes,***Protected Voter***,NaN,NaN,NaN,NaN,I,retired,CH,NaN,100.00,NaN,Holmes
239,57708,1,2026-07-15,E,Anedot,3723 Greenvville Ave,Suite 41002,Dallas,TX,75206.0,NaN,NaN,MO,Credit card fees,4.30,NaN,Anedot
240,57708,2,2026-07-15,E,Anedot,3723 Greenvville Ave,Suite 41002,Dallas,TX,75206.0,NaN,NaN,MO,Credit card fees,4.30,NaN,Anedot